In [1]:
import torch

### 실습1. 사이즈가 2 by 3인 tensor A, 동일하게 사이즈가 2 by 3인 tensor B를 생성하고, 
### B를 전치시켜 dot product 값을 구해보자.

In [2]:
A = torch.tensor([[0,1,2], [1,2,3]])
B = torch.tensor([[-1,0,1],[1,0,1]])
print(A)
print(B)

tensor([[0, 1, 2],
        [1, 2, 3]])
tensor([[-1,  0,  1],
        [ 1,  0,  1]])


In [3]:
B.transpose(0,1)

tensor([[-1,  1],
        [ 0,  0],
        [ 1,  1]])

In [4]:
torch.matmul(A, B.transpose(0,1))

tensor([[2, 2],
        [2, 4]])

### 실습2. 위의 문제에서 A가 여섯개 쌓인 tensor Q, B가 여섯개 쌓인 tensor K를 생성하고, 
### Q의 n번째 요소와 K의 n번째 요소끼리 dot product 시켜보자.

In [ ]:
Q=A.expand(6,2,3)
Q

In [ ]:
P=B.expand(6,2,3)

In [ ]:
P=B.transpose