In [1]:
import torch

### 임의의 텐서를 하나 생성합니다.

In [2]:
a = list(range(1,25))
x = torch.Tensor(a).view(2,3,4)
x

tensor([[[ 1.,  2.,  3.,  4.],
         [ 5.,  6.,  7.,  8.],
         [ 9., 10., 11., 12.]],

        [[13., 14., 15., 16.],
         [17., 18., 19., 20.],
         [21., 22., 23., 24.]]])

### 뷰(view)로 텐서의 차원 조작

In [3]:
# -1 을 넣으면 토치에서 알아서 계산해서, 제일 마지막 차원의 사이즈가 4가 되도록 맞춰줍니다.
x_view = x.view(-1, 4)    
print(x_view)
print(x_view.size())

tensor([[ 1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.],
        [ 9., 10., 11., 12.],
        [13., 14., 15., 16.],
        [17., 18., 19., 20.],
        [21., 22., 23., 24.]])
torch.Size([6, 4])


In [4]:
# 이런 식으로 중간에 넣어도 됩니다.
x_view = x.view(2,-1, 2)    
print(x_view)
print(x_view.size())

tensor([[[ 1.,  2.],
         [ 3.,  4.],
         [ 5.,  6.],
         [ 7.,  8.],
         [ 9., 10.],
         [11., 12.]],

        [[13., 14.],
         [15., 16.],
         [17., 18.],
         [19., 20.],
         [21., 22.],
         [23., 24.]]])
torch.Size([2, 6, 2])


In [5]:
# 근데 이렇게 '네가 알아서 계산해'를 두 개 이상 의뢰하면 도대체 어떻게 하란 거냐고 화냅니다. 우리 모두 적당히 합시다.
x_view = x.view(2,-1,-1, 2)    
print(x_view)
print(x_view.size())

RuntimeError: only one dimension can be inferred

In [6]:
# 제일 처음 설정한 x의 차원 사이즈는 [2,3,4]였어요. view 함수로 뒤의 두 차원에 대해 transpose도 할 수 있을까요?
x_view = x.view(2,4,3)
print(x_view)
print(x_view.size())

tensor([[[ 1.,  2.,  3.],
         [ 4.,  5.,  6.],
         [ 7.,  8.,  9.],
         [10., 11., 12.]],

        [[13., 14., 15.],
         [16., 17., 18.],
         [19., 20., 21.],
         [22., 23., 24.]]])
torch.Size([2, 4, 3])


-> 결과를 보시면 아시겠지만 안 됩니다. 차원 사이즈는 맞아보여도 이게 전치는 아니죠.

### transpose

In [7]:
# 그래서 등장한 transpose! 아래는 1번째 차원과 2번째 차원을 transpose 시켜달라는 요구입니다.
x_transpose = x.transpose(1, 2)  #[2,3,4]
print(x_transpose)
print(x_transpose.size())

tensor([[[ 1.,  5.,  9.],
         [ 2.,  6., 10.],
         [ 3.,  7., 11.],
         [ 4.,  8., 12.]],

        [[13., 17., 21.],
         [14., 18., 22.],
         [15., 19., 23.],
         [16., 20., 24.]]])
torch.Size([2, 4, 3])


-> 이게 transpose지!! 쾌감이 좀 느껴지네요

In [8]:
# transpose 안의 숫자를 뒤바꿔도 될까요? 됩니다.
x_transpose = x.transpose(2, 1)
print(x_transpose)
print(x_transpose.size())
# 어차피 두 개가 바뀌는 거니까 뭐가 먼저 나와도 상관 없습니다.

tensor([[[ 1.,  5.,  9.],
         [ 2.,  6., 10.],
         [ 3.,  7., 11.],
         [ 4.,  8., 12.]],

        [[13., 17., 21.],
         [14., 18., 22.],
         [15., 19., 23.],
         [16., 20., 24.]]])
torch.Size([2, 4, 3])


In [9]:
# 한편, 차원이 하나 더 깊어지게 하거나 사이즈가 1인 차원이면 밖으로 꺼내는 것도 있습니다. 이번에는 조금 다른 텐서를 만들어볼게요.
a = list(range(1, 9))
x = torch.Tensor(a).view(2,4)
x.size()
x
print(x.size())
x

torch.Size([2, 4])


tensor([[1., 2., 3., 4.],
        [5., 6., 7., 8.]])

In [10]:
# 깊어져라 얍!
x_unsqueeze = x.unsqueeze(0)
print(x_unsqueeze)
print(x_unsqueeze.size())

tensor([[[1., 2., 3., 4.],
         [5., 6., 7., 8.]]])
torch.Size([1, 2, 4])


In [11]:
# 얍!
x_unsqueeze = x.unsqueeze(1)
print(x_unsqueeze)
print(x_unsqueeze.size())

tensor([[[1., 2., 3., 4.]],

        [[5., 6., 7., 8.]]])
torch.Size([2, 1, 4])


In [12]:
# 얍!
x_unsqueeze = x.unsqueeze(2)
print(x_unsqueeze)
print(x_unsqueeze.size())

tensor([[[1.],
         [2.],
         [3.],
         [4.]],

        [[5.],
         [6.],
         [7.],
         [8.]]])
torch.Size([2, 4, 1])


In [13]:
# 얍!
x_unsqueeze = x.unsqueeze(3)
print(x_unsqueeze)
print(x_unsqueeze.size())
#  ... 적당히 합시다.

IndexError: Dimension out of range (expected to be in range of [-3, 2], but got 3)

### 실습0. 그럼 이제 unsqueezed 된 애들을 데리고 squeeze 하면서 어떻게 되는지 확인해보세요!