# 내 친구 torch를 소개합니다!

In [1]:
import torch

### 토치는 기본적으로 array적인 성격을 가지고 있는 아이에요

In [26]:
t1 = torch.arange(9)
# : tensor([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [27]:
t1

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [28]:
t1.shape
# torch.Size([9])

torch.Size([9])

In [29]:
type(t1)
# torch.Tensor

torch.Tensor

In [6]:
import numpy as np

In [10]:
arr = np.arange(9)

In [11]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [12]:
arr.shape

(9,)

In [13]:
type(arr)

numpy.ndarray

#### 그래서일까요? Numpy로의 변환도 쉽습니다.

In [31]:
# tensor를 numpy로 타입 변환
t1.numpy()
# array([0, 1, 2, 3, 4, 5, 6, 7, 8], dtype = int64)

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

#### Numpy가 하는 건 왠만하면 다 할 수 있습니다!

In [37]:
t1 = t1.reshape(3, 3)
t1
# tensor([ [0, 1, 2],
#           [3, 4, 5],
#           [6, 7, 8] ]])

tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])

In [33]:
t2 = torch.arange(9).reshape(3, 3)

In [34]:
t2

tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])

In [38]:
t1 + t2

tensor([[ 0,  2,  4],
        [ 6,  8, 10],
        [12, 14, 16]])

#### 그럼 여기서 질문이 생기겠죠?
Q. "아니, 넘파이 이용하면 되지, 왜 굳이 파이토치를 만든 거죠?"  
A. 000 때문에!

In [2]:
# 2차원 형태의 list를 이용하여 텐서를 생성할 수 있습니다.
torch.tensor([[1,2],[3,4.]])
# : tensor([[1., 2.],
#         [3., 4.]])

tensor([[1., 2.],
        [3., 4.]])

In [3]:
# device를 지정하면 GPU에 텐서를 만들 수 있습니다.
torch.tensor([[1,2],[3,4.]], device="cuda:0")
# : tensor([[1., 2.],
#         [3., 4.]], device='cuda:0')

tensor([[1., 2.],
        [3., 4.]], device='cuda:0')

In [4]:
# dtype을 이용하여 텐서의 데이터 형태를 지정할 수도 있습니다.
torch.tensor([[1,2],[3,4.]], dtype=torch.float64)
# : tensor([[1., 2.],
#         [3., 4.]], dtype=torch.float64)

tensor([[1., 2.],
        [3., 4.]], dtype=torch.float64)

In [5]:
# arange를 이용한 1차원 텐서
torch.arange(0, 10)
# : tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
# 모든 값이 0인 3 x 5의 텐서를 작성하여 to 메소드로 GPU에 전송
torch.zeros(3, 5).to("cuda:0")
# :tensor([[0., 0., 0., 0., 0.],
#         [0., 0., 0., 0., 0.],
#         [0., 0., 0., 0., 0.]], device='cuda:0')

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]], device='cuda:0')

In [10]:
# 모든 값이 1인 3 x 5의 텐서를 작성하여 to 메소드로 GPU에 전송
torch.ones(3, 5).to("cuda:0")
# :tensor([[1., 1., 1., 1., 1.],
#         [1., 1., 1., 1., 1.],
#         [1., 1., 1., 1., 1.]], device='cuda:0')

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]], device='cuda:0')

In [7]:
# normal distribution으로 3 x 5 텐서를 작성
torch.randn(3, 5)

tensor([[ 1.7086,  0.3570,  1.8505, -0.9447, -1.2399],
        [ 0.2351, -0.3140, -1.5484, -0.9172,  1.7181],
        [-0.2475,  0.6715, -0.0958, -0.8747,  0.6665]])

In [8]:
# 텐서의 shape은 size 메서드로 확인
t = torch.randn(3, 5)
t.size()
# : torch.Size([3, 5])

torch.Size([3, 5])

In [9]:
# GPU 상의 텐서는 to 메서드로 CPU의 텐서로 변환 후 ndarray로 변환해야 합니다.
t = torch.tensor([[1,2],[3,4.]], device="cuda:0")
x = t.to("cpu").numpy()

## 좋아... 배열의 성격을 가진다는 건 확실히 알겠어. 그럼 (모든 배열 구조가 그렇듯이) 인덱스로 자료에 접근이 가능하겠네? -> YES!!!😆

In [12]:
t = torch.tensor([
    [1,2,3],[4,5,6.]
])



In [13]:
# 인덱스 접근
t[0, 2]
# : tensor(3.)

tensor(3.)

In [14]:
# 슬라이스로 접근
t[:, :2]
# : tensor([[1., 2.],
#         [4., 5.]])

tensor([[ 1., 20.],
        [ 4., 20.]])

In [15]:
# 마스크 배열을 이용하여 True 값만 추출
t[t > 3]
# : tensor([4., 5., 6.])

tensor([20.,  4., 20., 20.])

In [16]:
# 슬라이스를 이용하여 일괄 대입
t[:, 1] = 10

In [ ]:
# 마스크 배열을 사용하여 일괄 대입
t[t > 5] = 20

## 근데 Numpy는 왠만한 연산이 다 가능하던데, 너도 가능하니? -> YES!!!😆

In [17]:
# 길이 3인 벡터
v = torch.tensor([1,2,3.])
w = torch.tensor([0, 10, 20])

In [18]:
# 2 x 3의 행렬
m = torch.tensor([
    [0, 1, 2], [100, 200, 300.]
])

In [19]:
# 벡터와 스칼라의 덧셈
v2 = v + 10

In [20]:
# 제곱
v2 = v ** 2

In [21]:
# 동일 길이의 벡터간 덧셈 연산
z =  v - w

In [22]:
# 여러 가지 조합
u = 2 * v - w / 10 + 6.0

In [23]:
# 행렬과 스칼라 곱
m2 = m * 2.0


In [24]:

# (2, 3)인 행렬과 (3,)인 벡터간의 덧셈이므로 브로드캐스팅 발생
m + v

# :tensor([[  1.,   3.,   5.],
#         [101., 202., 303.]])


tensor([[  1.,   3.,   5.],
        [101., 202., 303.]])

In [25]:
# 행렬 간 처리
m + m

# :tensor([[  0.,   2.,   4.],
#         [200., 400., 600.]])

tensor([[  0.,   2.,   4.],
        [200., 400., 600.]])

## 이렇게 멋진 친구를 내 손으로 만드는 방법 2가지!😆

### 첫번째, 사이즈만 정해주기!

#### 1-(1) "안에 들어가는 값이 뭐가 되든 일단 2 x 3의 텐서를 만들어줘봐!"

In [27]:
t1 = torch.rand(2,3)
print(t1)

tensor([[0.4489, 0.3527, 0.2917],
        [0.9933, 0.5119, 0.6011]])


#### 1-(2) "안에 들어가는 값이 0이 되도록 2 x 3의 텐서를 만들어줘봐!"

In [28]:
zeros = torch.zeros(2,3)

In [29]:
zeros

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [31]:
torch.zeros_like(t1)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

#### 1-(3) "안에 들어가는 값이 1이 되도록 2 x 3의 텐서를 만들어줘봐!"

In [33]:
ones = torch.ones(2,3)

In [34]:
ones

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [35]:
torch.ones_like(t1)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

### 두번째, 값을 지정해주기!

#### 2-(1) "리스트를 줄 테니 텐서를 다오"

In [38]:
ls = [
    [1,2,3],[4,5,6.]
]
t = torch.tensor(ls)
t

tensor([[1., 2., 3.],
        [4., 5., 6.]])

#### 2-(2) "넘파이 어레이를 줄 테니 텐서를 다오"

In [41]:
import numpy as np

In [44]:
arr = np.ndarray(shape=(2,3), dtype=int,buffer=np.array([1,2,3,4,5,6]))
# array([[1, 2, 3],
#        [4, 5, 6]])

In [46]:
t = torch.from_numpy(arr)
# tensor([[1, 2, 3],
#         [4, 5, 6]], dtype=torch.int32)
t

tensor([[1, 2, 3],
        [4, 5, 6]])

In [47]:
t.float()

tensor([[1., 2., 3.],
        [4., 5., 6.]])